CREATE DATABASE QLNS
GO
USE QLNS
GO

CREATE TABLE UUDAI
(
	MAUUUDAI INTEGER NOT NULL,
	TENUUDAI NVARCHAR(50),
	LOAIKHACHHANG NVARCHAR(50),
	UUDAI INTEGER,
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,
	CONSTRAINT pk_ud PRIMARY KEY (MAUUUDAI)
)

CREATE TABLE KHACHHANG
(
	MAKH INTEGER NOT NULL,
	TENKH NVARCHAR(50),
	DIACHI NVARCHAR(50),
	SDT INTEGER,
	EMAIL VARCHAR(50),
	MAUUDAI INTEGER,
	TIENNO INTEGER,
	CONSTRAINT pk_kh PRIMARY KEY (MAKH)
	--CONSTRAINT fk_kh FOREIGN KEY (MAUUDAI)
)

CREATE TABLE HOADON
(
	MAHOADON INTEGER NOT NULL,
	MAKHACHHANG INTEGER NOT NULL,
	NGAYLAP DATE,
	MANHANVIEN INTEGER NOT NULL,
	TONGTIEN INTEGER,
	DATHANHTOAN INTEGER,
	CONLAI INTEGER,
	CONSTRAINT pk_hd PRIMARY KEY (MAHOADON)
)

CREATE TABLE CHI_TIET_HOA_DON
(
	MAHOADON INTEGER NOT NULL,
	MASACH INTEGER NOT NULL,
	SOLUONG INTEGER,
	THANHTIEN INTEGER,
	CONSTRAINT pk_cthd PRIMARY KEY (MAHOADON,MASACH)
)

CREATE TABLE SACH
(
	MASACH INTEGER NOT NULL,
	TENSACH NVARCHAR(50),
	MATHELOAI INTEGER NOT NULL,
	TACGIA NVARCHAR(50),
	DONGIABAN INTEGER,
	CONSTRAINT pk_s PRIMARY KEY (MASACH,MATHELOAI)
)

CREATE TABLE THELOAI
(
	MATHELOAI INTEGER NOT NULL,
	TENTHELOAI NVARCHAR(50),
	CONSTRAINT pk_tl PRIMARY KEY (MATHELOAI)
)

CREATE TABLE KHO
(
	MASACH INTEGER NOT NULL,
	SOLUONGTON INTEGER,
	CONSTRAINT pk_k PRIMARY KEY (MASACH)
)

CREATE TABLE CHI_TIET_NHAP_SACH
(
	MAPHIEUNHAP INTEGER NOT NULL,
	MASACH INTEGER NOT NULL,
	SOLUONG INTEGER,
	GIANHAP INTEGER,
	THANHTIEN INTEGER,
	CONSTRAINT pk_ctns PRIMARY KEY (MAPHIEUNHAP,MASACH)
)

CREATE TABLE NHAPSACH
(
	MAPHIEUNHAP INTEGER NOT NULL,
	NGAYNHAP DATE,
	MANHANVIEN INTEGER NOT NULL,
	NOINHAP NVARCHAR(50),
	TONGTIEN INTEGER,
	CONSTRAINT pk_ns PRIMARY KEY (MAPHIEUNHAP,MANHANVIEN)
)

CREATE TABLE NHANVIEN
(
	MANHANVIEN INTEGER NOT NULL,
	TENNHANVIEN NVARCHAR(50),
	TENDANGNHAP NVARCHAR(50),
	MAQUYEN INTEGER NOT NULL,
	MANGUOIQUANLI INTEGER NOT NULL,
	LUONG INTEGER,
	MAPHUCAP INTEGER,
	CONSTRAINT pk_nv PRIMARY KEY (MANHANVIEN,MAQUYEN,MANGUOIQUANLI,MAPHUCAP)
)

CREATE TABLE PHIEUTHUTIEN
(
	MAPHIEUTHU INTEGER NOT NULL,
	MAKHACHHANG INTEGER NOT NULL,
	MANHANVIEN INTEGER NOT NULL,
	NGAYTHU DATE,
	SOTIENTHU INTEGER,
	CONSTRAINT pk_ptt PRIMARY KEY (MAPHIEUTHU,MAKHACHHANG,MANHANVIEN,NGAYTHU,SOTIENTHU) 
)

CREATE TABLE PHUCAP
(
	MAPHUCAP INTEGER NOT NULL,
	TENPHUCAP NVARCHAR(50),
	TIENTHUONG INTEGER,
	CONSTRAINT pk_pc PRIMARY KEY (MAPHUCAP)
)

CREATE TABLE QUYEN
(
	MAQUYEN INTEGER NOT NULL,
	CHUCVU NVARCHAR(50),
	CONSTRAINT pk_q PRIMARY KEY (MAQUYEN)
)

CREATE TABLE TAIKHOAN
(
	TENDANGNHAP NVARCHAR(50) NOT NULL,
	MATKHAU VARCHAR(50) NOT NULL,
	CONSTRAINT pk_tk PRIMARY KEY (TENDANGNHAP)
)

